### ISSUE TITLE
No funsiona

### ISSUE THREAD

**Issue by lamasumas** [flecktarn121/OS_SImulator#1]
Siento molestarle pero e intentado tirar el minecraft con intel celeron de primera generasion y no funsiona

**Comment by flecktarn121** [comment]
Che pibe, te voy a pasar un link de megaupload rechévere con el que podrás tirar lo que quieras. 
Link: www.adossis.es

**Comment by lamasumas** [comment]
Muxas grasias
jajaja salu2
subsribanse a mi canal plz
